#%RAML 1.0 Library

types:
  AddressData:
    type: object
    properties:
      personNumber?: string
      personNumberOld?: string
      addressType?: string
      addressTypeOld?: string
      addressEffectiveDate?: datetime
      addressEffectiveDateOld?: datetime
      addressLine1?: string
      addressLine1Old?: string
      addressLine2?: string
      addressLine2Old?: string
      addressLine3?: string
      addressLine3Old?: string
      addressLine4?: string
      addressLine4Old?: string      
      addressCity?: string
      addressCityOld?: string
      addressState?: string
      addressStateOld?: string
      zipCode?: string
      zipCodeOld?: string
      addressCountry?: string
      addressCountryOld?: string