#%RAML 1.0 Library

types:
  AllowancesData:
    type: object
    properties: 
      personNumber?: string
      personNumberOld?: string
      elementName?: string
      elementNameOld?: string
      elementValue?: string
      elementValueOld?: string
      elementStartDate?: datetime
      elementStartDateOld?: datetime
      elementEndDate?: datetime
      elementEndDateOld?: datetime