#%RAML 1.0 Library

types:
  AssignmentEitData:
    type: object
    properties: 
      personNumber?: string
      personNumberOld?: string
      dateClassification?: datetime
      dateClassificationOld?: datetime
      classification?: string
      classificationOld?: string
      percentImputation?: number
      percentImputationOld?: number
      imputation?: string
      imputationOld?: string