#%RAML 1.0 Library

types:
  AssignmentData:
    type: object
    properties: 
      personNumber?: string
      personNumberOld?: string
      hireDate?: datetime
      hireDateOld?: datetime
      terminationDate?: datetime
      terminationDateOld?: datetime
      actionName?: string
      actionNameOld?: string
      actionReason?: string
      actionReasonOld?: string
      actionEffectiveDate?: datetime
      actionEffectiveDateOld?: datetime
      employmentStatus?: string
      employmentStatusOld?: string
      employmentStatusMeaning?: string
      employmentStatusMeaningOld?: string
      legalEmployerHireDate?: datetime
      legalEmployerHireDateOld?: datetime
      enterpriseHireDate?: datetime
      enterpriseHireDateOld?: datetime
      seniorityDate?: datetime
      seniorityDateOld?: datetime
      workerType?: string
      workerTypeOld?: string
      personType?: string
      personTypeOld?: string
      businessUnit?: string
      businessUnitOld?: string
      department?: string
      departmentOld?: string
      job?: string
      jobOld?: string
      location?: string
      locationOld?: string
      grade?: string
      gradeOld?: string
      assignmentCategory?: string
      assignmentCategoryOld?: string
      workerCategory?: string
      workerCategoryOld?: string
      regularTemporary?: string
      regularTemporaryOld?: string
      hourlyOrSalaried?: string
      hourlyOrSalariedOld?: string
      fullTimePartTime?: string
      fullTimePartTimeOld?: string
      managerIndicator?: string
      managerIndicatorOld?: string
      fte?: number
      fteOld?: number
      assignmentType?: string
      assignmentTypeOld?: string
      projectedEndDate?: datetime
      projectedEndDateOld?: datetime
      probationEndDate?: datetime
      probationEndDateOld?: datetime
      noticePeriod?: number
      noticePeriodOld?: number
      noticePeriodUom?: string
      noticePeriodUomOld?: string
      outOfFranceResident?: string
      outOfFranceResidentOld?: string
      cchr?: string
      cchrOld?: string
      contractType?: string
      contractTypeOld?: string
      ottAgreementCode?: string
      ottAgreementCodeOld?: string
      contributorCategory?: string
      contributorCategoryOld?: string
      employment?: string
      employmentOld?: string
      natureContract?: string
      natureContractOld?: string
      durationLearning?: string
      durationLearningOld?: string