#%RAML 1.0 Library

types:
  BankAccountsData:
    type: object
    properties: 
      personNumber?: string
      personNumberOld?: string
      bankName?: string
      bankNameOld?: string
      bankBranchName?: string
      bankBranchNameOld?: string
      bankBranchNumber?: string
      bankBranchNumberOld?: string
      iban?: string
      ibanOld?: string
      swiftCode?: string
      swiftCodeOld?: string
      bankCountry?: string
      bankCountryOld?: string
      accountType?: string
      accountTypeOld?: string
      accountName?: string
      accountNameOld?: string
      accountNumber?: string
      accountNumberOld?: string
      paymentPercentage?: string
      paymentPercentageOld?: string
      paymentType?: string
      paymentTypeOld?: string
      currencyCode?: string
      currencyCodeOld?: string