#%RAML 1.0 Library

types:
  CitizenshipData:
    type: object
    properties: 
      personNumber?: string
      personNumberOld?: string
      nationality?: string
      nationalityOld?: string
      fromDate?: datetime
      fromDateOld?: datetime
      toDate?: datetime
      toDateOld?: datetime
      status?: string
      statusOld?: string