#%RAML 1.0 Library

types:
  DependentData:
    type: object
    properties:
      personNumber?: string
      personNumberOld?: string
      dependentPersonNumber?: string
      dependentPersonNumberOld?: string
      dependentRelationship?: string
      dependentRelationshipOld?: string
      dependentStartDate?: string
      dependentStartDateOld?: string
      dependentFirst_Name?: string
      dependentFirst_NameOld?: string
      dependentLast_Name?: string
      dependentLast_NameOld?: string
      dependentBirthDate?: string
      dependentBirthDateOld?: string
      dependentGender?: string
      dependentGenderOld?: string