#%RAML 1.0 Library

types:
  EmailData:
    type: object
    properties: 
      personNumber?: string
      personNumberOld?: string
      emailType?: string
      emailTypeOld?: string
      email?: string
      emailOld?: string