#%RAML 1.0 Library

types:
  IdentificationData:
    type: object
    properties:
      personNumber?: string
      personNumberOld?: string
      payrollNumber?: string
      payrollNumberOld?: string
      country?: string
      countryOld?: string
      legalEmployer?: string
      legalEmployerOld?: string