#%RAML 1.0 Library

types:
  ManagerData:
    type: object
    properties: 
      personNumber?: string
      personNumberOld?: string
      managerType?: string
      managerTypeOld?: string
      managerFirstName?: string
      managerFirstNameOld?: string
      managerLastName?: string
      managerLastNameOld?: string
      managerPersonNumber?: string
      managerPersonNumberOld?: string