#%RAML 1.0 Library

types:
  NidData:
    type: object
    properties: 
      personNumber?: string
      personNumberOld?: string
      nationalIdType?: string
      nationalIdTypeOld?: string
      nationalId?: string
      nationalIdOld?: string