#%RAML 1.0 Library

types:
  PassportData:
    type: object
    properties: 
      personNumber?: string
      person_NumberOld?: string
      passportIssueCountry?: string
      passportIssueCountryOld?: string
      passportType?: string
      passportTypeOld?: string
      passportNumber?: string
      passportNumberOld?: string
      passportIssuingAuthority?: string
      passportIssuingAuthorityOld?: string
      passportIssueDate?: datetime
      passportIssueDateOld?: datetime
      passportExpirationDate?: datetime
      passportExpirationDateOld?: datetime