#%RAML 1.0 Library

types:
  PersonalData:
    type: object
    properties: 
      personNumber?: string
      personNumberOld?: string
      title?: string
      titleOld?: string
      firstName?: string
      firstNameOld?: string
      middleName?: string
      middleNameOld?: string
      lastName?: string
      lastNameOld?: string
      dateOfBirth?: datetime
      dateOfBirthOld?: datetime
      dateOfDeath?: datetime
      dateOfDeathOld?: datetime
      countryOfBirth?: string
      countryOfBirthOld?: string
      regionOfBirth?: string
      regionOfBirthOld?: string
      townOfBirth?: string
      townOfBirthOld?: string
      correspondenceLanguage?: string
      correspondenceLanguageOld?: string
      bloodType?: string
      bloodTypeOld?: string
      gender?: string
      genderOld?: string
      maritalStatus?: string
      maritalStatusOld?: string
      maritalStatusDate?: datetime
      maritalStatusDateOld?: datetime
      highestEducationLevel?: string
      highestEducationLevelOld?: string
      ethnicity?: string
      ethnicityOld?: string