#%RAML 1.0 Library

types:
  PhoneData:
    type: object
    properties: 
      personNumber?: string
      personNumberOld?: string
      phoneType?: string
      phoneTypeOld?: string
      phoneNumber?: string
      phoneNumberOld?: string
      countryCode?: string
      countryCodeOld?: string
      areaCode?: string
      areaCodeOld?: string