#%RAML 1.0 Library

types:
  SalaryData:
    type: object
    properties:
      personNumber?: string
      personNumberOld?: string
      salaryAction?: string
      salaryActionOld?: string
      salaryActionReason?: string
      salaryActionReasonOld?: string
      salaryBasis?: string
      salaryBasisOld?: string
      fromDate?: datetime
      fromDateOld?: datetime
      toDate?: datetime
      toDateOld?: datetime
      salaryAnnualFactor?: number
      salaryAnnualFactorOld?: number
      salaryCurrency?: string
      salaryCurrencyOld?: string
      salaryAmount?: number
      salaryAmountOld?: number
      annualSalaryAmount?: number
      annualSalaryAmountOld?: number
      assignmentFte?: number
      assignmentFteOld?: number
      annualizedFteSalary?: number
      annualizedFteSalaryOld?: number