#%RAML 1.0 Library

types:
  VisaData:
    type: object
    properties: 
      personNumber?: string
      personNumberOld?: string
      visaIssueCountry?: string
      visaIssueCountryOld?: string
      visaType?: string
      visaTypeOld?: string
      visaCategory?: string
      visaCategoryOld?: string
      visaNumber?: string
      visaNumberOld?: string
      visaStatus?: string
      visaStatusOld?: string
      visaIssueDate?: datetime
      visaIssueDateOld?: datetime
      visaExpirationDate?: datetime
      visaExpirationDateOld?: datetime