#%RAML 1.0 DataType

#This file is located at dataTypes/SellingAgreement.raml

type: object
properties: 
  sellingAgreementId: integer
  fundNumber: 
    type: string
    required: false
  dstDealerNumber: 
    type: string
    required: false
  signingDate: 
    type: string
    required: false
  dstEffectiveDate: 
    type: string
    required: false
  firstEligibleCloseDate: 
    type: string
    required: false
  endDate: 
    type: string
    required: false
  commission: 
    type: number
    required: false
  fs2FeeDm: 
    type: number
    required: false
  bdReallowanceMarketingFee: 
    type: number
    required: false
  totalDmFee: 
    type: number
    required: false
  dealerCommission: 
    type: number
    required: false
  advancedCommission: 
    type: number
    required: false
  advancedMarketingFee: 
    type: number
    required: false
  socialCodes: 
    type: string
    required: false
  comments: 
    type: string
    required: false
  custodian: 
    type: string
    required: false
  uploadedDocumentUri: 
    type: string
    required: false
  saType: 
    type: string
    required: false
  createdBy: 
    type: string
    required: false
  createdOn: 
    type: string
    required: false
  modifiedBy: 
    type: string
    required: false
  modifiedOn: 
    type: string
    required: false