#%RAML 1.0 DataType

#This file is located at dataTypes/SellingAgreement.raml

type: object
properties: 
  sellingAgreementId: 
    type: integer
    required: false
  fundNumber: string
  dstDealerNumber: string
  signingDate: string
  dstEffectiveDate: string
  firstEligibleCloseDate: string
  endDate: string
  commission: number
  fs2FeeDm: number
  bdReallowanceMarketingFee: number
  totalDmFee: number
  dealerCommission: number
  advancedCommission: number
  advancedMarketingFee: number
  socialCodes: string
  comments: string
  custodian: string
  uploadedDocumentUri: string
  saType: string
  createdBy: string
  createdOn: string
  modifiedBy: string
  modifiedOn: string