#%RAML 0.8
title: MercuryGate System API
version: 1.0
baseUri: http://dev.esb.in.wcstar.com/transport/ux/myid/v1/

traits:
  - client-id-required:
      headers:
        client_id:
          type: string
        client_secret:
          type: string

/users:
  /tms:
    post:
      is: [client-id-required]
      description: Create a user
      body:
        application/json:
          example: !include examples/user-example.json
          schema: !include schemas/users-schema-input.json
      responses:
        202:
          description: Accepted
          body: 
            application/json: 
              example: !include examples/user-response-example.json